name: Test, Lint and Deploy
on:
  issues:
    - opened
    - edited
    - closed
    - reopened

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "${{ toJSON(github.event) }}"